export const PERMISSIONS = {
	GROUP_VIEW: "group:view",
	GROUP_EDIT: "group:edit",
	GROUP_DELETE: "group:delete",
	EXAM_CREATE: "exam:create",
	EXAM_EDIT: "exam:edit",
	EXAM_PUBLISH: "exam:publish",
	SUBMISSION_VIEW: "submission:view",
	SUBMISSION_GRADE: "submission:grade",
	ANALYTICS_VIEW: "analytics:view"
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_ALIASES: Record<PermissionKey, readonly string[]> = {
	[PERMISSIONS.GROUP_VIEW]: ["GROUP_VIEW"],
	[PERMISSIONS.GROUP_EDIT]: ["GROUP_EDIT"],
	[PERMISSIONS.GROUP_DELETE]: ["GROUP_DELETE"],
	[PERMISSIONS.EXAM_CREATE]: ["CREATE_EXAM"],
	[PERMISSIONS.EXAM_EDIT]: ["EDIT_EXAM"],
	[PERMISSIONS.EXAM_PUBLISH]: ["PUBLISH_EXAM"],
	[PERMISSIONS.SUBMISSION_VIEW]: ["VIEW_SUBMISSION"],
	[PERMISSIONS.SUBMISSION_GRADE]: ["GRADE_SUBMISSION"],
	[PERMISSIONS.ANALYTICS_VIEW]: ["VIEW_ANALYTICS"]
};
